import os
import boto3
from datetime import datetime
from config import S3_BUCKET
from scoring import health_score

# Create S3 client
s3 = boto3.client("s3")

# Ensure reports directory exists
os.makedirs("reports", exist_ok=True)


def generate_report(metrics, decision, reason, service):
    score, status = health_score(metrics)

    timestamp = datetime.utcnow().strftime("%d-%b-%Y %H:%M UTC")

    report = f"""
====================================================
      AI SELF-ADAPTIVE VPC HEALTH REPORT
====================================================

Timestamp      : {timestamp}

CloudWatch Metrics
------------------
CPU Usage      : {metrics['cpu']} %
Memory Usage   : {metrics['memory']} % (Simulated)
Disk Usage     : {metrics['disk']} % (Simulated)
Network In     : {metrics['network_in']} MB
Network Out    : {metrics['network_out']} MB

Health Score
------------
Score          : {score}/100
Status         : {status}

AI Recommendation
-----------------
Decision       : {decision}
Reason         : {reason}

Recommended AWS Service
-----------------------
{service}

====================================================
Generated by AI-Based Self-Adaptive Secure VPC Engine
====================================================
"""

    filename = f"reports/report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.txt"

    # Save locally
    with open(filename, "w") as file:
        file.write(report)

    # Upload to S3
    s3.upload_file(filename, S3_BUCKET, filename)

    print(report)
    print(f"\nReport uploaded successfully to S3 bucket: {S3_BUCKET}")

    return filename
